name: lint js css files
run-name: run js css files in ${{ github.repository }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - task/**
jobs:
  install_node_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm
      - name: Install dependencies
        run: npm ci
  linter_js_css_files:
    runs-on: ubuntu-latest
    needs: install_node_modules
    steps:
      - uses: actions/checkout@v3
      - name: Lint js files
        run: npm run lint
      - name: Run css files
        run: npm run lint:style