name: lint js css files
run-name: run js css files in ${{ github.repository }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - task/**
jobs:
  install_node_modules:
    uses: ./.github/workflows/install-node-modules.yml
  linter_js_css_files:
    runs-on: ubuntu-latest
    needs: install_node_modules
    steps:
      - uses: actions/checkout@v3
      - name: Get node_modules cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules-${{ runner.os }}
      - name: Lint js files
        run: npm run lint
      - name: Run css files
        run: npm run lint:style