name: Run unit tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
jobs:
  install_node_modules_call:
    uses: ./.github/workflows/install_node_modules.yml

  testing-files:
    runs-on: ubuntu-latest
    needs: install_node_modules_call
    steps:
      - uses: actions/checkout@v3
      - name: Get node_modules cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ github.sha }}-node-modules-${{ runner.os }}
      - name: testing js
        run: npm run test 
